import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type UILanguage = "es" | "en";

const translations = {
  es: {
    // Sidebar
    dashboard: "Inicio",
    createContent: "Crear contenido",
    calendar: "Calendario",
    shootingDay: "Día de grabación",
    library: "Biblioteca de contenido",
    settings: "Configuración",

    // Dashboard
    dashboardSubtitle: "Planifica y controla tu semana de contenido",
    business: "Negocio",
    startAddingBusiness: "Empieza añadiendo tu negocio en",
    whatToPublish: "¿Qué publico esta semana?",
    customizeWeeklyPlan: "Personaliza tu plan de contenido semanal",
    howManyPublications: "¿Cuántas publicaciones quieres esta semana?",
    contentTypePreference: "¿Qué tipo de contenido prefieres?",
    moreReels: "Más reels",
    balanced: "Equilibrado",
    morePosts: "Más posts",
    withCarousels: "Con carruseles",
    specialDatesOptional: "¿Hay fechas especiales esta semana? (opcional)",
    specialDatesPlaceholder: "Ej: Black Friday, aniversario del local, nueva carta...",
    generateWeeklyContent: "Generar mi contenido semanal",
    selectWeek: "Selecciona la semana",
    generatingPlan: "Generando plan...",
    yourWeeklyPlan: "Tu plan semanal",
    generate: "Generar",
    recentContent: "Contenido reciente",
    selectBusinessFirst: "Selecciona un negocio primero",
    weeklyPlanGenerated: "¡Plan semanal generado!",
    errorGeneratingPlan: "Error al generar plan",
    calendarNav: "Calendario",
    recordingDay: "Día de grabación",
    libraryNav: "Biblioteca de contenido",
    storiesIdeas: "Ideas de Stories",

    // Calendar
    calendarSubtitle: "Planifica y sigue tu contenido semana a semana",
    plans: "Planes",
    createdOn: "Creado el",
    previousWeek: "Semana anterior",
    nextWeek: "Semana siguiente",
    noPlansYet: "Sin planes aún",
    generateFirstPlan: "Genera tu primer plan semanal desde Inicio.",
    goToDashboard: "Ir a Inicio",
    generateWeeklyPlanBtn: "Generar plan semanal",
    reelIdeas: "Ideas de reels",
    hooks: "Hooks",
    generated: "generado",
    completed: "completado",
    markAsCompleted: "Marcar como completado",
    unmarkCompleted: "Desmarcar",
    editContent: "Editar contenido",
    generateThisContent: "Generar este contenido",
    loadingPlans: "Cargando planes...",
    weekOf: "Semana",

    // Create Content
    createContentSubtitle: "Crea una publicación individual de forma manual",
    backToCalendar: "Volver al calendario",
    contentType: "Tipo de contenido",
    post: "Post",
    reel: "Reel",
    carousel: "Carrusel",
    story: "Story",
    visualStyle: "Estilo visual",
    selectVisualStyle: "Seleccionar estilo visual",
    imageSource: "Origen de la imagen",
    generateWithAI: "Generar con IA",
    uploadImage: "Subir imagen",
    editWithAI: "Editar con IA",
    ideaOrTitle: "Idea o título *",
    ideaPlaceholder: "Ej: 5 tips para mejorar tu productividad",
    contextOptional: "Contexto (opcional)",
    describeContext: "Describe el contexto...",
    objective: "Objetivo",
    select: "Seleccionar",
    discover: "Descubrir",
    trust: "Confiar",
    buy: "Comprar",
    ctaLabel: "Llamada a la acción",
    ctaPlaceholder: "Ej: Guarda este post, Reserva ahora, Visita el link...",
    editWithAIDesc: "Sube una foto y la IA la mejorará o adaptará a tu estilo",
    generateContentBtn: "Generar contenido",
    generating: "Generando...",
    contentGenerated: "¡Contenido generado!",
    errorGenerating: "Error al generar",
    errorGeneratingImage: "Error al generar imagen",
    errorEditingImage: "Error al editar imagen",
    enterTitle: "Introduce un título",
    savedToLibrary: "Post guardado en la biblioteca de contenido",
    errorSaving: "Error al guardar",
    weeklyPlanContent: "Contenido del plan semanal",
    shots: "Planos",
    editInstructions: "Instrucciones de edición (opcional)...",

    // Shooting Day
    selectClient: "Selecciona un cliente",
    goToSettings: "Ve a Configuración para crear o seleccionar un cliente.",
    sessionFor: "Sesión para",
    fromWeeklyPlan: "Desde plan semanal",
    fromIdea: "Desde una idea",
    optimizeRecording: "Optimizar grabación",
    noWeeklyPlan: "Sin plan semanal",
    noWeeklyPlanDesc: "Primero genera tu plan de contenido semanal desde el Dashboard para poder organizar tu día de grabación.",
    contentToRecord: "Contenido a grabar",
    basedOnWeeklyPlan: "Basado en tu plan semanal del",
    howManyDays: "¿Cuántos días de grabación quieres planificar?",
    day: "día",
    days: "días",
    prepareSession: "Preparar sesión de grabación",
    organizingSession: "Organizando sesión...",
    describContentToRecord: "Describe el contenido que quieres grabar",
    customIdeaPlaceholder: "Ej: Unboxing mesa de comedor, Instalación de cocina, Preparación de plato especial, Presentación de producto...",
    generateRecordingPlan: "Generar plan de grabación",
    generatingPlanShort: "Generando plan...",
    optimizeWeekRecording: "Optimizar grabación de la semana",
    optimizeDesc: "Analiza todo el contenido planificado en tu calendario, identifica planos reutilizables y crea un plan de grabación eficiente.",
    optimizingSession: "Optimizando sesión...",
    shootingPlanGenerated: "¡Plan de grabación generado!",
    optimizedPlanGenerated: "¡Plan optimizado generado!",
    errorGeneratingShootingPlan: "Error al generar plan",
    writeIdeaFirst: "Escribe una idea o tema para grabar.",
    noWeeklyPlanToast: "No hay plan semanal. Genera uno primero desde el Dashboard.",
    sessionPlan: "Plan de sesión",
    contentInSession: "Contenido a grabar en esta sesión",
    reusableShots: "Planos reutilizables",
    reusableShotsDesc: "Graba estos planos una sola vez y úsalos en varios contenidos",
    optimizedRecordingOrder: "Orden de grabación optimizado",
    followSteps: "Sigue estos pasos para una sesión eficiente",
    totalShots: "planos totales",
    reusable: "reutilizables",
    storyboard: "Storyboard",
    onScreenText: "Textos en pantalla",
    sessionOrder: "Orden de la sesión",
    followStepsEfficient: "Sigue estos pasos para una grabación eficiente",
    supportShots: "Planos extra de apoyo",
    supportShotsDesc: "Graba estos planos adicionales para enriquecer tus reels",
    hook: "Hook",
    detailedStoryboard: "Storyboard detallado",
    eachStepDesc: "Cada paso describe exactamente qué grabar",
    shotList: "Lista de planos",
    recordingOrder: "Orden de grabación",
    recordingOrderDesc: "Orden óptimo para grabar (puede diferir del orden final del reel)",
    captionAndHashtags: "Caption y hashtags",
    estimatedDuration: "Duración estimada",
    order: "Orden",

    // Library
    librarySubtitle: "Accede y reutiliza todo el contenido que hayas guardado",
    posts: "Contenido generado",
    weeklyPlans: "Planes guardados",
    recordingSessions: "Guías de grabación",
    allBusinesses: "Todos",
    noContent: "Sin contenido guardado",
    generatedContentAppearsHere: "El contenido que generes y guardes aparecerá aquí.",
    noWeeklyPlans: "Sin planes guardados",
    plansAppearHere: "Los planes de contenido que guardes aparecerán aquí.",
    noRecordingSessions: "Sin guías de grabación",
    sessionsAppearHere: "Las guías de grabación que guardes aparecerán aquí.",
    contentDeleted: "Contenido eliminado",
    planDeleted: "Plan eliminado",
    backToLibrary: "Volver a la biblioteca",
    weekOfLabel: "Semana del",
    sessionOfDays: "Sesión de",
    reels: "reels",
    stories: "stories",

    // Settings
    myBusinesses: "Mis negocios",
    addBusiness: "Añadir negocio",
    addBusinessToStart: "Añade tu negocio para empezar a generar contenido.",
    editBusiness: "Editar negocio",
    newBusiness: "Nuevo negocio",
    businessName: "Nombre del negocio *",
    businessType: "Tipo de negocio",
    city: "Ciudad",
    cityPlaceholder: "Ej: Barcelona",
    contentLanguage: "Idioma del contenido",
    inspirationAccount: "Cuenta de inspiración (opcional)",
    inspirationPlaceholder: "Ej: @cuentainspiración",
    brandTone: "Tono de marca",
    tonePlaceholder: "Ej: cercano, profesional, elegante...",
    objectiveSetting: "Objetivo",
    objectivePlaceholder: "Ej: atraer clientes locales",
    visualStyleSetting: "Estilo visual",
    keywords: "Palabras clave (separadas por coma)",
    keywordsPlaceholder: "Ej: gourmet, vinos, local...",
    businessAddress: "Dirección del negocio (opcional)",
    addressPlaceholder: "Ej: Calle Mayor 12, Barcelona",
    update: "Actualizar",
    createBusiness: "Crear negocio",
    businessUpdated: "Negocio actualizado",
    businessCreated: "Negocio creado",
    businessDeleted: "Negocio eliminado",
    errorSavingBusiness: "Error al guardar",
    errorDeletingBusiness: "Error al eliminar",
    nameRequired: "El nombre es obligatorio",
    interfaceLanguage: "Idioma de la interfaz",
    interfaceLanguageDesc: "Cambia el idioma de los menús y botones de la aplicación. No afecta al idioma del contenido generado.",
    prepareShootingDay: "Preparar día de grabación",
    backToCalendarPrimary: "← Volver al calendario",
    generateAnotherPost: "Generar otro post",

    // Settings - delete confirmation
    deleteBusinessTitle: "¿Eliminar negocio?",
    deleteBusinessWarning: "Esta acción es irreversible. Se eliminará el negocio y toda su configuración.",
    cancel: "Cancelar",
    confirmDelete: "Eliminar",

    // Strategy
    strategy: "Estrategia",
    strategyPlanningFor: "Planificación para",
    strategyWeeklyCalendar: "Calendario semanal",
    strategyWeeklyCalendarDesc: "Consulta y gestiona tus planes de contenido",
    strategyReelIdeas: "Ideas de reels",
    strategyReelIdeasDesc: "Genera 10 ideas de reels adaptadas a tu negocio",
    strategyHookGenerator: "Generador de hooks",
    strategyHookGeneratorDesc: "Crea hooks irresistibles para tus contenidos",
    strategyContentMatrix: "Matriz de contenido",
    strategyEducational: "Educativo",
    strategyTipsTutorials: "Tips, tutoriales",
    strategyProcessExpertise: "Procesos, expertise",
    strategyComparativesGuides: "Comparativas, guías",
    strategyEntertainment: "Entretenimiento",
    strategyTrendsHumor: "Tendencias, humor",
    strategyBehindScenes: "Behind the scenes",
    strategyExperiencesUGC: "Experiencias, UGC",
    strategyProduct: "Producto",
    strategyDemosReveals: "Demos, reveals",
    strategyTestimonialsCases: "Testimonios, casos",
    strategyOffersCTAs: "Ofertas, CTAs directos",

    // Carousel
    carouselSlideCount: "¿Cuántas imágenes quieres en el carrusel?",
    carouselSlides: "imágenes",
    carouselSlideOf: "de",
    generatingImages: "Generando imágenes...",
    generatingImageN: "Generando imagen",
    regenerateAll: "Regenerar todas",
  },
  en: {
    // Sidebar
    dashboard: "Home",
    createContent: "Create content",
    calendar: "Calendar",
    shootingDay: "Recording day",
    library: "Content Library",
    settings: "Settings",

    // Dashboard
    dashboardSubtitle: "Plan and control your content week",
    business: "Business",
    startAddingBusiness: "Start by adding your business in",
    whatToPublish: "What should I post this week?",
    customizeWeeklyPlan: "Customize your weekly content plan",
    howManyPublications: "How many publications do you want this week?",
    contentTypePreference: "What type of content do you prefer?",
    moreReels: "More reels",
    balanced: "Balanced",
    morePosts: "More posts",
    withCarousels: "With carousels",
    specialDatesOptional: "Any special dates this week? (optional)",
    specialDatesPlaceholder: "E.g.: Black Friday, store anniversary, new menu...",
    generateWeeklyContent: "Generate my weekly content",
    selectWeek: "Select the week",
    generatingPlan: "Generating plan...",
    yourWeeklyPlan: "Your weekly plan",
    generate: "Generate",
    recentContent: "Recent content",
    selectBusinessFirst: "Select a business first",
    weeklyPlanGenerated: "Weekly plan generated!",
    errorGeneratingPlan: "Error generating plan",
    calendarNav: "Calendar",
    recordingDay: "Recording day",
    libraryNav: "Content Library",
    storiesIdeas: "Stories ideas",

    // Calendar
    calendarSubtitle: "Plan and track your content week by week",
    plans: "Plans",
    createdOn: "Created on",
    previousWeek: "Previous week",
    nextWeek: "Next week",
    noPlansYet: "No plans yet",
    generateFirstPlan: "Generate your first weekly plan from the Dashboard.",
    goToDashboard: "Go to Dashboard",
    generateWeeklyPlanBtn: "Generate weekly plan",
    reelIdeas: "Reel ideas",
    hooks: "Hooks",
    generated: "generated",
    completed: "completed",
    markAsCompleted: "Mark as completed",
    unmarkCompleted: "Unmark",
    editContent: "Edit content",
    generateThisContent: "Generate this content",
    loadingPlans: "Loading plans...",
    weekOf: "Week",

    // Create Content
    createContentSubtitle: "Create a single piece of content manually",
    backToCalendar: "Back to calendar",
    contentType: "Content type",
    post: "Post",
    reel: "Reel",
    carousel: "Carousel",
    story: "Story",
    visualStyle: "Visual style",
    selectVisualStyle: "Select visual style",
    imageSource: "Image source",
    generateWithAI: "Generate with AI",
    uploadImage: "Upload image",
    editWithAI: "Edit with AI",
    ideaOrTitle: "Idea or title *",
    ideaPlaceholder: "E.g.: 5 tips to improve productivity",
    contextOptional: "Context (optional)",
    describeContext: "Describe the context...",
    objective: "Objective",
    select: "Select",
    discover: "Discover",
    trust: "Trust",
    buy: "Buy",
    ctaLabel: "Call to action",
    ctaPlaceholder: "E.g.: Save this post, Book now, Visit the link...",
    editWithAIDesc: "Upload a photo and AI will enhance or adapt it to your style",
    generateContentBtn: "Generate content",
    generating: "Generating...",
    contentGenerated: "Content generated!",
    errorGenerating: "Error generating",
    errorGeneratingImage: "Error generating image",
    errorEditingImage: "Error editing image",
    enterTitle: "Enter a title",
    savedToLibrary: "Post saved to content library",
    errorSaving: "Error saving",
    weeklyPlanContent: "Weekly plan content",
    shots: "Shots",
    editInstructions: "Edit instructions (optional)...",

    // Shooting Day
    selectClient: "Select a client",
    goToSettings: "Go to Settings to create or select a client.",
    sessionFor: "Session for",
    fromWeeklyPlan: "From weekly plan",
    fromIdea: "From an idea",
    optimizeRecording: "Optimize recording",
    noWeeklyPlan: "No weekly plan",
    noWeeklyPlanDesc: "First generate your weekly content plan from the Dashboard to organize your recording day.",
    contentToRecord: "Content to record",
    basedOnWeeklyPlan: "Based on your weekly plan from",
    howManyDays: "How many recording days do you want to plan?",
    day: "day",
    days: "days",
    prepareSession: "Prepare recording session",
    organizingSession: "Organizing session...",
    describContentToRecord: "Describe the content you want to record",
    customIdeaPlaceholder: "E.g.: Dining table unboxing, Kitchen installation, Special dish preparation...",
    generateRecordingPlan: "Generate recording plan",
    generatingPlanShort: "Generating plan...",
    optimizeWeekRecording: "Optimize weekly recording",
    optimizeDesc: "Analyzes all planned content in your calendar, identifies reusable shots and creates an efficient recording plan.",
    optimizingSession: "Optimizing session...",
    shootingPlanGenerated: "Recording plan generated!",
    optimizedPlanGenerated: "Optimized plan generated!",
    errorGeneratingShootingPlan: "Error generating plan",
    writeIdeaFirst: "Write an idea or topic to record.",
    noWeeklyPlanToast: "No weekly plan. Generate one first from the Dashboard.",
    sessionPlan: "Session plan",
    contentInSession: "Content to record in this session",
    reusableShots: "Reusable shots",
    reusableShotsDesc: "Record these shots once and use them in multiple contents",
    optimizedRecordingOrder: "Optimized recording order",
    followSteps: "Follow these steps for an efficient session",
    totalShots: "total shots",
    reusable: "reusable",
    storyboard: "Storyboard",
    onScreenText: "On-screen text",
    sessionOrder: "Session order",
    followStepsEfficient: "Follow these steps for efficient recording",
    supportShots: "Extra support shots",
    supportShotsDesc: "Record these extra shots to enrich your reels",
    hook: "Hook",
    detailedStoryboard: "Detailed storyboard",
    eachStepDesc: "Each step describes exactly what to record",
    shotList: "Shot list",
    recordingOrder: "Recording order",
    recordingOrderDesc: "Optimal order for recording (may differ from final reel order)",
    captionAndHashtags: "Caption & hashtags",
    estimatedDuration: "Estimated duration",
    order: "Order",

    // Library
    posts: "Generated content",
    weeklyPlans: "Saved plans",
    recordingSessions: "Recording guides",
    allBusinesses: "All",
    noContent: "No saved content",
    generatedContentAppearsHere: "Content you generate and save will appear here.",
    noWeeklyPlans: "No saved plans",
    plansAppearHere: "Content plans you save will appear here.",
    noRecordingSessions: "No recording guides",
    sessionsAppearHere: "Recording guides you save will appear here.",
    contentDeleted: "Content deleted",
    planDeleted: "Plan deleted",
    backToLibrary: "Back to library",
    weekOfLabel: "Week of",
    sessionOfDays: "Session of",
    reels: "reels",
    stories: "stories",

    // Settings
    myBusinesses: "My businesses",
    addBusiness: "Add business",
    addBusinessToStart: "Add your business to start generating content.",
    editBusiness: "Edit business",
    newBusiness: "New business",
    businessName: "Business name *",
    businessType: "Business type",
    city: "City",
    cityPlaceholder: "E.g.: Barcelona",
    contentLanguage: "Content language",
    inspirationAccount: "Inspiration account (optional)",
    inspirationPlaceholder: "E.g.: @inspirationaccount",
    brandTone: "Brand tone",
    tonePlaceholder: "E.g.: friendly, professional, elegant...",
    objectiveSetting: "Objective",
    objectivePlaceholder: "E.g.: attract local customers",
    visualStyleSetting: "Visual style",
    keywords: "Keywords (comma-separated)",
    keywordsPlaceholder: "E.g.: gourmet, wines, local...",
    businessAddress: "Business address (optional)",
    addressPlaceholder: "E.g.: 12 Main Street, Barcelona",
    update: "Update",
    createBusiness: "Create business",
    businessUpdated: "Business updated",
    businessCreated: "Business created",
    businessDeleted: "Business deleted",
    errorSavingBusiness: "Error saving",
    errorDeletingBusiness: "Error deleting",
    nameRequired: "Name is required",
    interfaceLanguage: "Interface language",
    interfaceLanguageDesc: "Changes the language of app menus and buttons. Does not affect generated content language.",
    prepareShootingDay: "Prepare recording day",
    backToCalendarPrimary: "← Back to calendar",
    generateAnotherPost: "Generate another post",

    // Settings - delete confirmation
    deleteBusinessTitle: "Delete business?",
    deleteBusinessWarning: "This action is irreversible. The business and all its configuration will be deleted.",
    cancel: "Cancel",
    confirmDelete: "Delete",

    // Strategy
    strategy: "Strategy",
    strategyPlanningFor: "Planning for",
    strategyWeeklyCalendar: "Weekly calendar",
    strategyWeeklyCalendarDesc: "View and manage your content plans",
    strategyReelIdeas: "Reel ideas",
    strategyReelIdeasDesc: "Generate 10 reel ideas tailored to your business",
    strategyHookGenerator: "Hook generator",
    strategyHookGeneratorDesc: "Create irresistible hooks for your content",
    strategyContentMatrix: "Content matrix",
    strategyEducational: "Educational",
    strategyTipsTutorials: "Tips, tutorials",
    strategyProcessExpertise: "Processes, expertise",
    strategyComparativesGuides: "Comparatives, guides",
    strategyEntertainment: "Entertainment",
    strategyTrendsHumor: "Trends, humor",
    strategyBehindScenes: "Behind the scenes",
    strategyExperiencesUGC: "Experiences, UGC",
    strategyProduct: "Product",
    strategyDemosReveals: "Demos, reveals",
    strategyTestimonialsCases: "Testimonials, cases",
    strategyOffersCTAs: "Offers, direct CTAs",

    // Carousel
    carouselSlideCount: "How many images do you want in the carousel?",
    carouselSlides: "images",
    carouselSlideOf: "of",
    generatingImages: "Generating images...",
    generatingImageN: "Generating image",
    regenerateAll: "Regenerate all",
  },
} as const;

export type TranslationKey = keyof typeof translations.es;

interface LanguageContextType {
  uiLanguage: UILanguage;
  setUILanguage: (lang: UILanguage) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  uiLanguage: "es",
  setUILanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [uiLanguage, setUILanguage] = useState<UILanguage>(() => {
    return (localStorage.getItem("ui-language") as UILanguage) || "es";
  });

  useEffect(() => {
    localStorage.setItem("ui-language", uiLanguage);
  }, [uiLanguage]);

  const t = (key: TranslationKey): string => {
    return translations[uiLanguage][key] || translations.es[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ uiLanguage, setUILanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
